version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: imagecropper_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=image_cropper
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: imagecropper_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge